using System;
using System.Text;
using System.Threading;
using MultiShell.Models;
using MultiShell.Services;
using SvcSystems.UI.Terminal;

namespace MultiShell.ViewModels;

public partial class TerminalTabViewModel
{
    private readonly AnsiStreamProcessor _ansiStreamProcessor = new();
    private readonly StringBuilder _pendingUiFeedBuffer = new();
    private readonly Lock _pendingUiFeedLock = new();
    private readonly StringBuilder _inputLineBuffer = new();
    private bool _isUiFeedScheduled;
    private bool _previousWasCr;

    /// <summary>
    /// Indicates whether AltGr (Ctrl+Alt modifier) is currently pressed.
    /// Used to suppress false-positive Control characters generated by the terminal control during AltGr key combos.
    /// </summary>
    public bool IsAltGrActive { get; set; }

    /// <summary>
    /// Checks if incoming text from the shell contains terminal color queries (OSC 10 foreground, OSC 11 background)
    /// emitted by TUIs such as Neovim, and responds back to the shell with the active theme RGB colors.
    /// </summary>
    internal void CheckAndRespondToOscColorQueries(string text)
    {
        AnsiStreamProcessor.DispatchOscColorQueries(text, IsDarkTerminalTheme, response =>
        {
            try
            {
                _session.Send(Encoding.ASCII.GetBytes(response));
            }
            catch { }
        });
    }

    /// <summary>
    /// Strips unsupported OSC escape sequences (e.g. OSC 8 hyperlinks, OSC 9/133 shell integration)
    /// to prevent terminal controls from misparsing them and printing stray ']' characters at column 0.
    /// </summary>
    public static string SanitizeTerminalText(string text) =>
        AnsiStreamProcessor.SanitizeTerminalText(text);

    /// <summary>
    /// Finds the start index of an incomplete ANSI/VT100 escape sequence at the end of the text stream,
    /// or -1 if the text ends with complete escape sequences / plain characters.
    /// Used to buffer fragmented sequences across stream chunks and prevent color bleeding and render corruption.
    /// </summary>
    public static int FindIncompleteEscapeSequenceIndex(string text) =>
        AnsiStreamProcessor.FindIncompleteEscapeSequenceIndex(text);

    private void OnSessionDataReceived(byte[] data)
    {
        if (_isDisposed || data.Length == 0) return;

        string? textToFeed = _ansiStreamProcessor.ProcessChunk(
            data,
            onOscColorResponse: response =>
            {
                try
                {
                    _session.Send(Encoding.ASCII.GetBytes(response));
                }
                catch { }
            },
            isDarkTheme: IsDarkTerminalTheme);

        if (string.IsNullOrEmpty(textToFeed) || _isDisposed) return;

        if (Avalonia.Application.Current == null || Avalonia.Threading.Dispatcher.UIThread.CheckAccess())
        {
            // Direct synchronous feed when running in unit tests or already on UI thread
            if (!_isDisposed)
            {
                TerminalModel.Feed(textToFeed);
            }
        }
        else
        {
            // Coalesce rapid PTY chunks onto the UI thread at Render priority to eliminate intermediate blank frames and flicker (REQ-TERM-011)
            lock (_pendingUiFeedLock)
            {
                if (_isDisposed) return;
                _pendingUiFeedBuffer.Append(textToFeed);
                if (!_isUiFeedScheduled)
                {
                    _isUiFeedScheduled = true;
                    Avalonia.Threading.Dispatcher.UIThread.Post(FlushPendingUiFeed, Avalonia.Threading.DispatcherPriority.Render);
                }
            }
        }
    }

    /// <summary>
    /// Flushes all accumulated PTY stream chunks to the terminal model in a single batched pass on the UI thread.
    /// Eliminates TUI flicker caused by separate rendering of line-erase and text-write chunks.
    /// </summary>
    internal void FlushPendingUiFeed()
    {
        if (_isDisposed) return;
        string batchText;
        lock (_pendingUiFeedLock)
        {
            _isUiFeedScheduled = false;
            if (_isDisposed || _pendingUiFeedBuffer.Length == 0) return;
            batchText = _pendingUiFeedBuffer.ToString();
            _pendingUiFeedBuffer.Clear();
        }

        if (!_isDisposed)
        {
            TerminalModel.Feed(batchText);
        }
    }

    private void OnTerminalUserInput(object? sender, TerminalUserInputEventArgs e)
    {
        if (!IsRunning || e.Data.IsEmpty) return;

        var bytes = e.Data.ToArray();

        // When AltGr (Ctrl+Alt) is active on international keyboards (e.g. AltGr+Q for '@', AltGr+E for '€'),
        // SvcSystems.UI.Terminal misidentifies the key as Ctrl+Q (0x11) / Ctrl+E (0x05) in OnKeyDown.
        // We filter out these single control bytes so only the valid TextInput character (@, €, etc.) is sent.
        if (IsAltGrActive && bytes.Length == 1 && bytes[0] < 32 && bytes[0] != 9 && bytes[0] != 10 && bytes[0] != 13)
        {
            return;
        }

        // Track user input line for live CommandHistory tracking
        TrackInputBuffer(bytes);

        _session.Send(bytes);
    }

    private void TrackInputBuffer(byte[] bytes)
    {
        if (bytes.Length == 0 || bytes[0] == 0x1B) return;

        char[] chars;
        try
        {
            chars = Encoding.UTF8.GetChars(bytes);
        }
        catch
        {
            return;
        }

        lock (_inputLineBuffer)
        {
            foreach (var ch in chars)
            {
                if (ch == '\x03') // Ctrl+C -> cancel line
                {
                    _previousWasCr = false;
                    _inputLineBuffer.Clear();
                    continue;
                }

                if (ch == '\r') // Enter / Return: command execution
                {
                    _previousWasCr = true;
                    string executedCommand = _inputLineBuffer.ToString().Trim();
                    _inputLineBuffer.Clear();

                    if (!string.IsNullOrWhiteSpace(executedCommand))
                    {
                        _pendingCommandDirectory = WorkingDirectory;
                        if (ShellType != ShellType.PowerShell)
                        {
                            OnSessionCommandExecuted(executedCommand);
                            CheckForDirectoryChangeCommand(executedCommand);
                        }
                    }
                    continue;
                }

                if (ch == '\n')
                {
                    if (_previousWasCr)
                    {
                        // CRLF sequence - already executed on '\r'
                        _previousWasCr = false;
                        continue;
                    }

                    // Standalone linefeed (e.g. Shift+Enter / Ctrl+Enter multi-line script continuation)
                    _inputLineBuffer.Append('\n');
                    continue;
                }

                _previousWasCr = false;

                if (ch == '\b' || ch == '\x7F') // Backspace
                {
                    if (_inputLineBuffer.Length > 0)
                    {
                        _inputLineBuffer.Length--;
                    }
                    continue;
                }

                if (!char.IsControl(ch))
                {
                    _inputLineBuffer.Append(ch);
                }
            }
        }
    }

    private void OnTerminalSizeChanged(object? sender, TerminalSizeChangedEventArgs e)
    {
        if (!IsRunning) return;

        if (e.Cols > 0 && e.Rows > 0)
        {
            _session.Resize(e.Cols, e.Rows);
        }
    }
}
