using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> EnglishStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Settings & About",
        ["Settings_App_Theme"] = "App UI Theme",
        ["Settings_Terminal_Theme"] = "Terminal Theme",
        ["Settings_Language"] = "Language",
        ["Settings_App_FontSize"] = "App Font Size",
        ["Settings_Terminal_FontSize"] = "Terminal Font Size",
        ["Settings_Profiles_Title"] = "Terminal Profiles...",
        ["Settings_Help_Title"] = "Help & Shortcuts",
        ["Settings_About_Title"] = "About MultiShell",
        ["Theme_Dark"] = "Dark",
        ["Theme_Light"] = "Light",
        ["FontSize_Level_1"] = "Very Small (1)",
        ["FontSize_Level_2"] = "Small (2)",
        ["FontSize_Level_3"] = "Standard (3)",
        ["FontSize_Level_4"] = "Large (4)",
        ["FontSize_Level_5"] = "Very Large (5)",
        ["FontSize_Default_Badge"] = "Standard",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "New Tab (Ctrl+Shift+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "New {0} Tab (Ctrl+Shift+T)",
        ["Btn_Select_Shell_Tooltip"] = "Select Terminal Type",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Command Prompt (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Tab History (Ctrl+Shift+H / Ctrl+Shift+L)",
        ["Btn_Tab_History_Text"] = "History",
        ["Btn_Tab_Menu_Tooltip"] = "Open Tabs Overview (Ctrl+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Scroll Tabs Left",
        ["Btn_Tab_Scroll_Right"] = "Scroll Tabs Right",
        ["Btn_Tab_Close_Tooltip"] = "Close Tab (Ctrl+Shift+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "OPEN TABS",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Shift+Tab ▴  |  Release Ctrl to Open  |  Esc Cancel ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Navigate  |  Click/Enter Open  |  Esc Close ]",
        ["Tab_Switcher_Count"] = "{0} of {1} Tabs",

        // Drawer
        ["Drawer_Title"] = "HISTORY",
        ["Drawer_Tab_Commands"] = "Commands",
        ["Drawer_Tab_Directories"] = "Directories",
        ["Drawer_Tab_Global"] = "Global",
        ["Drawer_Search_Commands_Placeholder"] = "Filter commands...",
        ["Drawer_Search_Directories_Placeholder"] = "Filter directories...",
        ["Drawer_Search_Global_Placeholder"] = "Filter all commands & paths...",
        ["Drawer_Empty_Commands"] = "No commands executed in this tab yet.",
        ["Drawer_Empty_Directories"] = "No directories recorded in this tab yet.",
        ["Drawer_Empty_Global"] = "No commands or directories recorded yet.",
        ["Drawer_Hint"] = "[ ▲/▼ Navigate  |  Click/Enter Insert  |  Right-Click Execute  |  Esc Close ]",

        // Help Modal
        ["Help_Modal_Title"] = "Keyboard Shortcuts & Usage",
        ["Help_Section_Navigation"] = "SHORTCUTS",
        ["Help_Section_Tabs"] = "TAB MANAGEMENT",
        ["Help_Section_History"] = "HISTORY OVERLAY",
        ["Help_Section_Features"] = "FEATURES",
        ["Help_Close_Button"] = "Close",
        ["Help_Tab_New"] = "Open new PowerShell tab",
        ["Help_Tab_Dup"] = "Duplicate active tab in current directory",
        ["Help_Tab_Next_Prev"] = "Select next / previous tab (cycle)",
        ["Help_Tab_Jump"] = "Jump directly to tab 1..8 or last tab (9)",
        ["Help_Tab_Close"] = "Close active tab",
        ["Help_Tab_Move"] = "Move active tab left / right",
        ["Help_Term_Newline"] = "Insert newline in terminal without executing command",
        ["Help_Zoom_Shortcuts"] = "Zoom terminal font in / out / reset to default (also Ctrl+MouseWheel)",
        ["Help_Scroll_Shortcuts"] = "Scroll up / down through terminal buffer",
        ["Help_Buffer_Clear"] = "Clear terminal screen and scrollback buffer",
        ["Help_Copy_Paste"] = "Copy / paste text without signal interruption",
        ["Help_Hist_Toggle"] = "Toggle History Overlay (Navigate with ▲/▼, Enter)",
        ["Help_Hist_Commands"] = "Toggle command history drawer (▲/▼, Enter)",
        ["Help_Hist_Directories"] = "Toggle directory history drawer (▲/▼, Enter)",
        ["Help_Hist_Global"] = "Toggle global history drawer (▲/▼, Enter)",
        ["Help_Search_Terminal"] = "Open/close in-terminal search (Ctrl+Shift+F / Ctrl+Shift+F3, Esc)",
        ["Help_Pick_File"] = "Select file and insert path (Ctrl+Shift+O)",
        ["Help_Pick_Folder"] = "Select folder and insert path (Ctrl+Shift+B)",
        ["Help_Open_Explorer"] = "Open file browser in current folder (Ctrl+Shift+E)",
        ["Help_Nav_F1"] = "Open this Help dialog (Ctrl+Shift+F1)",
        ["Help_Nav_Esc"] = "Close active overlay / dialog and focus terminal",
        ["Help_Feature_1"] = "• Tab History: Hover left edge or press Ctrl+Shift+H (Commands) / Ctrl+Shift+L (Directories). Left-click/Enter to insert, right-click to execute.",
        ["Help_Feature_2"] = "• Drag & Drop: Reorder tabs by dragging with left mouse button.",
        ["Help_Feature_3"] = "• Tab Overflow: Scroll buttons (‹ ›) and quick menu (≡ ▾) appear when tab count exceeds window.",
        ["Help_Feature_4"] = "• Zoom: Ctrl++, Ctrl+-, Ctrl+0 or Ctrl+MouseWheel to dynamically scale terminal font size.",
        ["Help_Feature_5"] = "• Persistence: All tabs, working directories, and histories persist automatically across restarts.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "High Performance PowerShell Workspace",
        ["About_Version"] = "Version:",
        ["About_Framework"] = "Framework:",
        ["About_UI_Terminal"] = "UI & Terminal:",
        ["About_License"] = "License:",
        ["About_GitHub"] = "GitHub Repository:",
        ["About_Built_With"] = "Built With:",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Crafted with Clean Architecture & Clean Code principles.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Terminal Profiles",
        ["Profiles_Modal_Subtitle"] = "Configure terminal profiles, paths, arguments and add custom shells",
        ["Profiles_Btn_Add"] = "+ New Profile",
        ["Profiles_Btn_Edit"] = "Edit",
        ["Profiles_Btn_Delete"] = "Delete",
        ["Profiles_Btn_Save"] = "Save",
        ["Profiles_Btn_Cancel"] = "Cancel",
        ["Profiles_Btn_Reset"] = "Reset to Defaults",
        ["Profiles_Btn_Browse"] = "Browse...",
        ["Profiles_Browse_Exe_Title"] = "Select Executable File",
        ["Profiles_Browse_Dir_Title"] = "Select Working Directory",
        ["Dialog_PickFile_Title"] = "Select File (Insert Path)",
        ["Dialog_PickFolder_Title"] = "Select Folder (Insert Path)",
        ["Profiles_Field_Name"] = "Profile Name",
        ["Profiles_Field_Path"] = "Executable Path",
        ["Profiles_Field_WorkingDir"] = "Working Directory (Default: User Profile)",
        ["Profiles_Field_Args"] = "Arguments (optional)",
        ["Profiles_Field_Icon"] = "Badge Tag (e.g. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Shell Emulation Type",
        ["Profiles_Edit_Title"] = "Edit Profile",
        ["Profiles_Create_Title"] = "Create New Profile",
        ["Profiles_Empty"] = "No profiles configured.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "No Active Terminal Tabs",
        ["EmptyState_Description"] = "Select a terminal profile below or start a new session using shortcuts.",
        ["EmptyState_QuickLaunch"] = "QUICK LAUNCH",
        ["EmptyState_ShortcutsHint"] = "[ Ctrl+T New Tab  |  Ctrl+Shift+T Profile Menu  |  Ctrl+Shift+F1 Help ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Recently Closed Tabs",
        ["ClosedTabs_RestoreTooltip"] = "Restore tab with history",
        ["ClosedTabs_RemoveTooltip"] = "Remove from history",
        ["ClosedTabs_ClearAll"] = "Clear History",
        ["ClosedTabs_EmptyStateTitle"] = "Recently Closed Tabs",
        ["ClosedTabs_EmptyHint"] = "No closed tabs in history",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Find in terminal...",
        ["Search_Terminal_Previous"] = "Previous match (Shift+Enter)",
        ["Search_Terminal_Next"] = "Next match (Enter / Ctrl+Shift+F3)",
        ["Search_Terminal_Close"] = "Close search (Esc)",
        ["Search_Terminal_NoResults"] = "No results",
        ["Search_Terminal_Matches"] = "{0} of {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Rename Tab",
        ["Menu_Tab_ResetName"] = "Reset Tab Name",
        ["Menu_Tab_Color"] = "Tab Color",
        ["Menu_Tab_Duplicate"] = "Duplicate Tab",
        ["Menu_Tab_OpenInExplorer"] = "Open in File Explorer",
        ["Menu_Tab_Close"] = "Close Tab",
        ["Menu_Tab_CloseOthers"] = "Close Other Tabs",
        ["Menu_Tab_CloseRight"] = "Close Tabs to the Right",
        ["Color_Default"] = "Default (No Color)",
        ["Color_Red"] = "Red",
        ["Color_Orange"] = "Orange",
        ["Color_Yellow"] = "Yellow",
        ["Color_Green"] = "Green",
        ["Color_Cyan"] = "Cyan",
        ["Color_Blue"] = "Blue",
        ["Color_Purple"] = "Purple",
        ["Color_Pink"] = "Pink"
    };
}
