using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> ItalianStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Impostazioni & Informazioni",
        ["Settings_App_Theme"] = "Tema applicazione",
        ["Settings_Terminal_Theme"] = "Tema terminale",
        ["Settings_Language"] = "Lingua",
        ["Settings_App_FontSize"] = "Dimensione carattere app",
        ["Settings_Terminal_FontSize"] = "Dimensione carattere terminale",
        ["Settings_Profiles_Title"] = "Profili terminale...",
        ["Settings_Help_Title"] = "Guida & Scorciatoie",
        ["Settings_About_Title"] = "Informazioni su MultiShell",
        ["Theme_Dark"] = "Scuro",
        ["Theme_Light"] = "Chiaro",
        ["FontSize_Level_1"] = "Molto piccolo (1)",
        ["FontSize_Level_2"] = "Piccolo (2)",
        ["FontSize_Level_3"] = "Standard (3)",
        ["FontSize_Level_4"] = "Grande (4)",
        ["FontSize_Level_5"] = "Molto grande (5)",
        ["FontSize_Default_Badge"] = "Standard",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "Nuova scheda (Ctrl+Shift+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "Nuova scheda {0} (Ctrl+Shift+T)",
        ["Btn_Select_Shell_Tooltip"] = "Seleziona tipo di terminale",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Prompt dei comandi (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Cronologia scheda (Ctrl+Shift+H / Ctrl+Shift+L)",
        ["Btn_Tab_History_Text"] = "Cronologia",
        ["Btn_Tab_Menu_Tooltip"] = "Panoramica schede (Ctrl+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Scorri schede a sinistra",
        ["Btn_Tab_Scroll_Right"] = "Scorri schede a destra",
        ["Btn_Tab_Close_Tooltip"] = "Chiudi scheda (Ctrl+Shift+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "SCHEDE APERTE",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Shift+Tab ▴  |  Rilascia Ctrl per aprire  |  Esc Annulla ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Naviga  |  Clic/Invio Apri  |  Esc Chiudi ]",
        ["Tab_Switcher_Count"] = "{0} di {1} schede",

        // Drawer
        ["Drawer_Title"] = "CRONOLOGIA",
        ["Drawer_Tab_Commands"] = "Comandi",
        ["Drawer_Tab_Directories"] = "Directory",
        ["Drawer_Tab_Global"] = "Globale",
        ["Drawer_Search_Commands_Placeholder"] = "Filtra comandi...",
        ["Drawer_Search_Directories_Placeholder"] = "Filtra directory...",
        ["Drawer_Search_Global_Placeholder"] = "Filtra tutti i comandi e percorsi...",
        ["Drawer_Empty_Commands"] = "Nessun comando eseguito in questa scheda.",
        ["Drawer_Empty_Directories"] = "Nessuna directory registrata in questa scheda.",
        ["Drawer_Empty_Global"] = "Nessun comando o percorso registrato.",
        ["Drawer_Hint"] = "[ ▲/▼ Naviga  |  Clic/Invio Inserisci  |  Clic destro Esegui  |  Esc Chiudi ]",

        // Help Modal
        ["Help_Modal_Title"] = "Scorciatoie da tastiera & Utilizzo",
        ["Help_Section_Navigation"] = "SCORCIATOIE",
        ["Help_Section_Tabs"] = "GESTIONE SCHEDE",
        ["Help_Section_History"] = "PANNELLO CRONOLOGIA",
        ["Help_Section_Features"] = "FUNZIONALITÀ",
        ["Help_Close_Button"] = "Chiudi",
        ["Help_Tab_New"] = "Apri nuova scheda PowerShell",
        ["Help_Tab_Dup"] = "Duplica scheda attiva nella directory corrente",
        ["Help_Tab_Next_Prev"] = "Seleziona scheda successiva / precedente",
        ["Help_Tab_Jump"] = "Passa direttamente alla scheda 1..8 o all'ultima (9)",
        ["Help_Tab_Close"] = "Chiudi scheda attiva",
        ["Help_Tab_Move"] = "Sposta scheda attiva a sinistra / destra",
        ["Help_Term_Newline"] = "Inserisci nuova riga nel terminale senza eseguire comando",
        ["Help_Zoom_Shortcuts"] = "Zoom carattere terminale avanti / indietro / reimposta (anche Ctrl+Rotellina)",
        ["Help_Scroll_Shortcuts"] = "Scorri in alto / in basso nel buffer del terminale",
        ["Help_Buffer_Clear"] = "Cancella schermo e buffer di scorrimento del terminale",
        ["Help_Copy_Paste"] = "Copia / incolla testo senza interruzione del segnale",
        ["Help_Hist_Toggle"] = "Attiva pannello cronologia (Naviga con ▲/▼, Invio)",
        ["Help_Hist_Commands"] = "Attiva cronologia comandi (▲/▼, Invio)",
        ["Help_Hist_Directories"] = "Attiva cronologia directory (▲/▼, Invio)",
        ["Help_Hist_Global"] = "Attiva cronologia globale (▲/▼, Invio)",
        ["Help_Search_Terminal"] = "Apri/chiudi ricerca nel terminale (Ctrl+Maiusc+F / Ctrl+Maiusc+F3, Esc)",
        ["Help_Pick_File"] = "Seleziona file e inserisci percorso (Ctrl+Maiusc+O)",
        ["Help_Pick_Folder"] = "Seleziona cartella e inserisci percorso (Ctrl+Maiusc+E)",
        ["Help_Nav_F1"] = "Apri questa finestra di guida (Ctrl+Maiusc+F1)",
        ["Help_Nav_Esc"] = "Chiudi finestra / dialogo attivo e focalizza il terminale",
        ["Help_Feature_1"] = "• Cronologia scheda: Passa il mouse sul bordo sinistro o premi Ctrl+Shift+H (Comandi) / Ctrl+Shift+L (Directory). Clic sinistro/Invio per inserire, clic destro per eseguire.",
        ["Help_Feature_2"] = "• Trascina & Rilascia: Riordina le schede trascinandole con il tasto sinistro del mouse.",
        ["Help_Feature_3"] = "• Schede in eccesso: I pulsanti di scorrimento (‹ ›) e il menu rapido (≡ ▾) appaiono quando le schede superano la finestra.",
        ["Help_Feature_4"] = "• Zoom: Ctrl++, Ctrl+-, Ctrl+0 o Ctrl+Rotellina per ridimensionare dinamicamente il carattere.",
        ["Help_Feature_5"] = "• Persistenza: Tutte le schede, directory di lavoro e cronologie persistono automaticamente tra i riavvii.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "Ambiente di lavoro PowerShell ad alte prestazioni",
        ["About_Version"] = "Versione:",
        ["About_Framework"] = "Framework:",
        ["About_UI_Terminal"] = "UI & Terminale:",
        ["About_License"] = "Licenza:",
        ["About_GitHub"] = "Repository GitHub:",
        ["About_Built_With"] = "Creato con:",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Progettato secondo i principi di Clean Architecture & Clean Code.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Profili terminale",
        ["Profiles_Modal_Subtitle"] = "Configura profili terminale, percorsi, argomenti e aggiungi shell personalizzate",
        ["Profiles_Btn_Add"] = "+ Nuovo profilo",
        ["Profiles_Btn_Edit"] = "Modifica",
        ["Profiles_Btn_Delete"] = "Elimina",
        ["Profiles_Btn_Save"] = "Salva",
        ["Profiles_Btn_Cancel"] = "Annulla",
        ["Profiles_Btn_Reset"] = "Ripristina predefiniti",
        ["Profiles_Btn_Browse"] = "Sfoglia...",
        ["Profiles_Browse_Exe_Title"] = "Seleziona file eseguibile",
        ["Profiles_Browse_Dir_Title"] = "Seleziona directory di lavoro",
        ["Dialog_PickFile_Title"] = "Seleziona file (inserisci percorso)",
        ["Dialog_PickFolder_Title"] = "Seleziona cartella (inserisci percorso)",
        ["Profiles_Field_Name"] = "Nome profilo",
        ["Profiles_Field_Path"] = "Percorso eseguibile",
        ["Profiles_Field_WorkingDir"] = "Directory di lavoro (predefinita: cartella utente)",
        ["Profiles_Field_Args"] = "Argomenti (facoltativo)",
        ["Profiles_Field_Icon"] = "Etichetta badge (es. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Tipo di emulazione shell",
        ["Profiles_Edit_Title"] = "Modifica profilo",
        ["Profiles_Create_Title"] = "Crea nuovo profilo",
        ["Profiles_Empty"] = "Nessun profilo configurato.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "Nessuna scheda terminale attiva",
        ["EmptyState_Description"] = "Seleziona un profilo terminale in basso o avvia una nuova sessione con le scorciatoie.",
        ["EmptyState_QuickLaunch"] = "AVVIO RAPIDO",
        ["EmptyState_ShortcutsHint"] = "[ Ctrl+T Nuova scheda  |  Ctrl+Maiusc+T Menu profili  |  Ctrl+Maiusc+F1 Guida ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Schede chiuse di recente",
        ["ClosedTabs_RestoreTooltip"] = "Ripristina scheda con cronologia",
        ["ClosedTabs_RemoveTooltip"] = "Rimuovi dalla cronologia",
        ["ClosedTabs_ClearAll"] = "Cancella cronologia",
        ["ClosedTabs_EmptyStateTitle"] = "Schede chiuse di recente",
        ["ClosedTabs_EmptyHint"] = "Nessuna scheda chiusa nella cronologia",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Cerca nel terminale...",
        ["Search_Terminal_Previous"] = "Corrispondenza precedente (Maiusc+Invio)",
        ["Search_Terminal_Next"] = "Corrispondenza successiva (Invio / Ctrl+Maiusc+F3)",
        ["Search_Terminal_Close"] = "Chiudi ricerca (Esc)",
        ["Search_Terminal_NoResults"] = "Nessun risultato",
        ["Search_Terminal_Matches"] = "{0} di {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Rinomina scheda",
        ["Menu_Tab_ResetName"] = "Ripristina nome scheda",
        ["Menu_Tab_Color"] = "Colore scheda",
        ["Menu_Tab_Duplicate"] = "Duplica scheda",
        ["Menu_Tab_Close"] = "Chiudi scheda",
        ["Menu_Tab_CloseOthers"] = "Chiudi altre schede",
        ["Menu_Tab_CloseRight"] = "Chiudi schede a destra",
        ["Color_Default"] = "Predefinito (nessun colore)",
        ["Color_Red"] = "Rosso",
        ["Color_Orange"] = "Arancione",
        ["Color_Yellow"] = "Giallo",
        ["Color_Green"] = "Verde",
        ["Color_Cyan"] = "Ciano",
        ["Color_Blue"] = "Blu",
        ["Color_Purple"] = "Viola",
        ["Color_Pink"] = "Rosa"
    };
}
