using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> GermanStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Einstellungen & Über",
        ["Settings_App_Theme"] = "App-Design",
        ["Settings_Terminal_Theme"] = "Terminal-Design",
        ["Settings_Language"] = "Sprache",
        ["Settings_App_FontSize"] = "App-Schriftgröße",
        ["Settings_Terminal_FontSize"] = "Terminal-Schriftgröße",
        ["Settings_Profiles_Title"] = "Terminal-Profile...",
        ["Settings_Help_Title"] = "Hilfe & Tastaturkürzel",
        ["Settings_About_Title"] = "Über MultiShell",
        ["Theme_Dark"] = "Dunkel",
        ["Theme_Light"] = "Hell",
        ["FontSize_Level_1"] = "Sehr klein (1)",
        ["FontSize_Level_2"] = "Klein (2)",
        ["FontSize_Level_3"] = "Standard (3)",
        ["FontSize_Level_4"] = "Groß (4)",
        ["FontSize_Level_5"] = "Sehr groß (5)",
        ["FontSize_Default_Badge"] = "Standard",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "Neuer Tab (Strg+Umschalt+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "Neuer {0}-Tab (Strg+Umschalt+T)",
        ["Btn_Select_Shell_Tooltip"] = "Terminal-Typ auswählen",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Eingabeaufforderung (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Tab-Verlauf (Strg+Umschalt+H / Strg+Umschalt+L)",
        ["Btn_Tab_History_Text"] = "Verlauf",
        ["Btn_Tab_Menu_Tooltip"] = "Tab-Übersicht (Strg+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Tabs nach links scrollen",
        ["Btn_Tab_Scroll_Right"] = "Tabs nach rechts scrollen",
        ["Btn_Tab_Close_Tooltip"] = "Tab schließen (Strg+Umschalt+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "TAB-ÜBERSICHT",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Umschalt+Tab ▴  |  Strg loslassen zum Öffnen  |  Esc Abbrechen ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Navigieren  |  Klick/Enter Öffnen  |  Esc Schließen ]",
        ["Tab_Switcher_Count"] = "{0} von {1} Tabs",

        // Drawer
        ["Drawer_Title"] = "VERLAUF",
        ["Drawer_Tab_Commands"] = "Befehle",
        ["Drawer_Tab_Directories"] = "Verzeichnisse",
        ["Drawer_Tab_Global"] = "Global",
        ["Drawer_Search_Commands_Placeholder"] = "Befehle filtern...",
        ["Drawer_Search_Directories_Placeholder"] = "Verzeichnisse filtern...",
        ["Drawer_Search_Global_Placeholder"] = "Alle Befehle & Pfade filtern...",
        ["Drawer_Empty_Commands"] = "In diesem Tab wurden noch keine Befehle ausgeführt.",
        ["Drawer_Empty_Directories"] = "In diesem Tab wurden noch keine Verzeichnisse erfasst.",
        ["Drawer_Empty_Global"] = "Es wurden noch keine Befehle oder Pfade erfasst.",
        ["Drawer_Hint"] = "[ ▲/▼ Navigieren  |  Klick/Enter Übernehmen  |  Rechtsklick Ausführen  |  Esc Schließen ]",

        // Help Modal
        ["Help_Modal_Title"] = "Tastaturkürzel & Bedienung",
        ["Help_Section_Navigation"] = "TASTATURKÜRZEL",
        ["Help_Section_Tabs"] = "TAB-VERWALTUNG",
        ["Help_Section_History"] = "VERLAUFS-DRAWER",
        ["Help_Section_Features"] = "FUNKTIONEN",
        ["Help_Close_Button"] = "Schließen",
        ["Help_Tab_New"] = "Neuen PowerShell-Tab öffnen",
        ["Help_Tab_Dup"] = "Aktiven Tab im aktuellen Verzeichnis duplizieren",
        ["Help_Tab_Next_Prev"] = "Nächsten / vorherigen Tab auswählen (zyklisch)",
        ["Help_Tab_Jump"] = "Direkt zu Tab 1..8 bzw. letztem Tab (9) springen",
        ["Help_Tab_Close"] = "Aktiven Tab schließen",
        ["Help_Tab_Move"] = "Aktiven Tab nach links / rechts verschieben",
        ["Help_Term_Newline"] = "Zeilenumbruch im Terminal einfügen (ohne Ausführung)",
        ["Help_Zoom_Shortcuts"] = "Terminal-Schriftgröße vergrößern / verkleinern / zurücksetzen",
        ["Help_Scroll_Shortcuts"] = "Im Terminal-Puffer nach oben / unten blättern",
        ["Help_Buffer_Clear"] = "Terminal-Bildschirm und Scrollback-Puffer leeren",
        ["Help_Copy_Paste"] = "Text kopieren / einfügen (ohne Signalunterbrechung)",
        ["Help_Hist_Toggle"] = "Verlaufs-Overlay öffnen/schließen (▲/▼, Enter)",
        ["Help_Hist_Commands"] = "Befehlsverlauf öffnen/schließen (▲/▼, Enter)",
        ["Help_Hist_Directories"] = "Verzeichnisverlauf öffnen/schließen (▲/▼, Enter)",
        ["Help_Hist_Global"] = "Globalen Verlauf öffnen/schließen (▲/▼, Enter)",
        ["Help_Search_Terminal"] = "Terminal-Textsuche öffnen/schließen (Strg+Umschalt+F / Strg+Umschalt+F3, Esc)",
        ["Help_Pick_File"] = "Datei auswählen und Pfad einfügen (Strg+Umschalt+O)",
        ["Help_Pick_Folder"] = "Ordner auswählen und Pfad einfügen (Strg+Umschalt+E)",
        ["Help_Nav_F1"] = "Diesen Hilfe-Dialog öffnen (Strg+Umschalt+F1)",
        ["Help_Nav_Esc"] = "Aktives Overlay/Dialog schließen und Terminal fokussieren",
        ["Help_Feature_1"] = "• Tab-Verlauf: Linke Kante berühren oder Strg+Umschalt+H (Befehle) / Strg+Umschalt+L (Verzeichnisse) drücken. Mit Klick/Enter übernehmen, per Rechtsklick direkt ausführen.",
        ["Help_Feature_2"] = "• Drag & Drop: Tabs mit der linken Maustaste per Ziehen neu anordnen.",
        ["Help_Feature_3"] = "• Tab-Überlauf: Scrollbuttons (‹ ›) und Schnellmenü (≡ ▾) bei vielen Tabs.",
        ["Help_Feature_4"] = "• Zoom: Strg++, Strg+-, Strg+0 oder Strg+Mausrad zum dynamischen Skalieren der Terminalgröße.",
        ["Help_Feature_5"] = "• Persistenz: Alle Tabs, Pfade und Verläufe werden automatisch gespeichert.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "High-Performance PowerShell Workspace",
        ["About_Version"] = "Version:",
        ["About_Framework"] = "Framework:",
        ["About_UI_Terminal"] = "UI & Terminal:",
        ["About_License"] = "Lizenz:",
        ["About_Font"] = "Terminal-Schriftart:",
        ["About_Font_Value"] = "FiraCode Nerd Font Mono (OFL-1.1)",
        ["About_Third_Party"] = "Drittanbieter-Lizenzen:",
        ["About_Third_Party_Value"] = "THIRD_PARTY_NOTICES.md (OFL, MIT)",
        ["About_GitHub"] = "GitHub-Repository:",
        ["About_Built_With"] = "Entwickelt mit:",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Entwickelt nach den Prinzipien von Clean Architecture & Clean Code.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Terminal-Profile",
        ["Profiles_Modal_Subtitle"] = "Profile konfigurieren, Pfade anpassen und neue Terminals hinzufügen",
        ["Profiles_Btn_Add"] = "+ Neues Profil",
        ["Profiles_Btn_Edit"] = "Bearbeiten",
        ["Profiles_Btn_Delete"] = "Löschen",
        ["Profiles_Btn_Save"] = "Speichern",
        ["Profiles_Btn_Cancel"] = "Abbrechen",
        ["Profiles_Btn_Reset"] = "Standard zurücksetzen",
        ["Profiles_Btn_Browse"] = "Durchsuchen...",
        ["Profiles_Browse_Exe_Title"] = "Ausführbare Datei auswählen",
        ["Profiles_Browse_Dir_Title"] = "Startverzeichnis auswählen",
        ["Dialog_PickFile_Title"] = "Datei auswählen (Pfad einfügen)",
        ["Dialog_PickFolder_Title"] = "Ordner auswählen (Pfad einfügen)",
        ["Profiles_Field_Name"] = "Profilname",
        ["Profiles_Field_Path"] = "Pfad zur ausführbaren Datei",
        ["Profiles_Field_WorkingDir"] = "Startverzeichnis (Standard: Benutzerverzeichnis)",
        ["Profiles_Field_Args"] = "Startargumente (optional)",
        ["Profiles_Field_Icon"] = "Badge-Kürzel (z. B. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Shell-Emulationstyp",
        ["Profiles_Edit_Title"] = "Profil bearbeiten",
        ["Profiles_Create_Title"] = "Neues Profil anlegen",
        ["Profiles_Empty"] = "Keine Profile vorhanden.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "Keine aktiven Terminal-Tabs",
        ["EmptyState_Description"] = "Wähle ein Terminal-Profil aus oder starte eine neue Sitzung per Tastenkürzel.",
        ["EmptyState_QuickLaunch"] = "SCHNELLSTART",
        ["EmptyState_ShortcutsHint"] = "[ Strg+T Neuer Tab  |  Strg+Umschalt+T Profilauswahl  |  Strg+Umschalt+F1 Hilfe ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Zuletzt geschlossene Tabs",
        ["ClosedTabs_RestoreTooltip"] = "Tab mit Verlauf wiederherstellen",
        ["ClosedTabs_RemoveTooltip"] = "Aus Verlauf entfernen",
        ["ClosedTabs_ClearAll"] = "Verlauf leeren",
        ["ClosedTabs_EmptyStateTitle"] = "Zuletzt geschlossene Tabs",
        ["ClosedTabs_EmptyHint"] = "Keine geschlossenen Tabs im Verlauf",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Im Terminal suchen...",
        ["Search_Terminal_Previous"] = "Vorheriger Treffer (Umschalt+Eingabe)",
        ["Search_Terminal_Next"] = "Nächster Treffer (Eingabe / Strg+Umschalt+F3)",
        ["Search_Terminal_Close"] = "Suche schließen (Esc)",
        ["Search_Terminal_NoResults"] = "Keine Treffer",
        ["Search_Terminal_Matches"] = "{0} von {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Tab umbenennen",
        ["Menu_Tab_ResetName"] = "Tab-Namen zurücksetzen",
        ["Menu_Tab_Color"] = "Tab-Farbe",
        ["Menu_Tab_Duplicate"] = "Tab duplizieren",
        ["Menu_Tab_Close"] = "Tab schließen",
        ["Menu_Tab_CloseOthers"] = "Andere Tabs schließen",
        ["Menu_Tab_CloseRight"] = "Tabs rechts schließen",
        ["Color_Default"] = "Standard (Keine Farbe)",
        ["Color_Red"] = "Rot",
        ["Color_Orange"] = "Orange",
        ["Color_Yellow"] = "Gelb",
        ["Color_Green"] = "Grün",
        ["Color_Cyan"] = "Cyan",
        ["Color_Blue"] = "Blau",
        ["Color_Purple"] = "Lila",
        ["Color_Pink"] = "Rosa"
    };
}
