using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> FrenchStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Paramètres & À propos",
        ["Settings_App_Theme"] = "Thème de l'application",
        ["Settings_Terminal_Theme"] = "Thème du terminal",
        ["Settings_Language"] = "Langue",
        ["Settings_App_FontSize"] = "Taille de police de l'app",
        ["Settings_Terminal_FontSize"] = "Taille de police du terminal",
        ["Settings_Profiles_Title"] = "Profils de terminal...",
        ["Settings_Help_Title"] = "Aide & Raccourcis",
        ["Settings_About_Title"] = "À propos de MultiShell",
        ["Theme_Dark"] = "Sombre",
        ["Theme_Light"] = "Clair",
        ["FontSize_Level_1"] = "Très petit (1)",
        ["FontSize_Level_2"] = "Petit (2)",
        ["FontSize_Level_3"] = "Standard (3)",
        ["FontSize_Level_4"] = "Grand (4)",
        ["FontSize_Level_5"] = "Très grand (5)",
        ["FontSize_Default_Badge"] = "Standard",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "Nouvel onglet (Ctrl+Maj+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "Nouvel onglet {0} (Ctrl+Maj+T)",
        ["Btn_Select_Shell_Tooltip"] = "Sélectionner le type de terminal",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Invite de commandes (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Historique des onglets (Ctrl+Maj+H / Ctrl+Maj+L)",
        ["Btn_Tab_History_Text"] = "Historique",
        ["Btn_Tab_Menu_Tooltip"] = "Aperçu des onglets (Ctrl+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Faire défiler les onglets à gauche",
        ["Btn_Tab_Scroll_Right"] = "Faire défiler les onglets à droite",
        ["Btn_Tab_Close_Tooltip"] = "Fermer l'onglet (Ctrl+Maj+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "APERÇU DES ONGLETS",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Maj+Tab ▴  |  Relâcher Ctrl pour ouvrir  |  Échap Annuler ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Naviguer  |  Clic/Entrée Ouvrir  |  Échap Fermer ]",
        ["Tab_Switcher_Count"] = "{0} sur {1} onglets",

        // Drawer
        ["Drawer_Title"] = "HISTORIQUE",
        ["Drawer_Tab_Commands"] = "Commandes",
        ["Drawer_Tab_Directories"] = "Répertoires",
        ["Drawer_Tab_Global"] = "Global",
        ["Drawer_Search_Commands_Placeholder"] = "Filtrer les commandes...",
        ["Drawer_Search_Directories_Placeholder"] = "Filtrer les répertoires...",
        ["Drawer_Search_Global_Placeholder"] = "Filtrer toutes les commandes & chemins...",
        ["Drawer_Empty_Commands"] = "Aucune commande exécutée dans cet onglet.",
        ["Drawer_Empty_Directories"] = "Aucun répertoire enregistré dans cet onglet.",
        ["Drawer_Empty_Global"] = "Aucune commande ou aucun répertoire enregistré.",
        ["Drawer_Hint"] = "[ ▲/▼ Naviguer  |  Clic/Entrée Insérer  |  Clic droit Exécuter  |  Échap Fermer ]",

        // Help Modal
        ["Help_Modal_Title"] = "Raccourcis clavier & Utilisation",
        ["Help_Section_Navigation"] = "RACCOURCIS",
        ["Help_Section_Tabs"] = "GESTION DES ONGLETS",
        ["Help_Section_History"] = "VOLET HISTORIQUE",
        ["Help_Section_Features"] = "FONCTIONNALITÉS",
        ["Help_Close_Button"] = "Fermer",
        ["Help_Tab_New"] = "Ouvrir un nouvel onglet PowerShell",
        ["Help_Tab_Dup"] = "Dupliquer l'onglet actif dans le répertoire actuel",
        ["Help_Tab_Next_Prev"] = "Sélectionner l'onglet suivant / précédent (cycle)",
        ["Help_Tab_Jump"] = "Aller directement à l'onglet 1..8 ou au dernier (9)",
        ["Help_Tab_Close"] = "Fermer l'onglet actif",
        ["Help_Tab_Move"] = "Déplacer l'onglet actif à gauche / droite",
        ["Help_Term_Newline"] = "Insérer un saut de ligne sans exécuter la commande",
        ["Help_Zoom_Shortcuts"] = "Agrandir / réduire / réinitialiser la police du terminal (ou Ctrl+Molette)",
        ["Help_Scroll_Shortcuts"] = "Défiler vers le haut / bas dans le tampon du terminal",
        ["Help_Buffer_Clear"] = "Effacer l'écran et le tampon de défilement du terminal",
        ["Help_Copy_Paste"] = "Copier / coller le texte sans interruption de signal",
        ["Help_Hist_Toggle"] = "Afficher/Masquer le volet d'historique (▲/▼, Entrée)",
        ["Help_Hist_Commands"] = "Afficher/Masquer l'historique des commandes (▲/▼, Entrée)",
        ["Help_Hist_Directories"] = "Afficher/Masquer l'historique des répertoires (▲/▼, Entrée)",
        ["Help_Hist_Global"] = "Afficher/Masquer l'historique global (▲/▼, Entrée)",
        ["Help_Search_Terminal"] = "Ouvrir/fermer la recherche dans le terminal (Ctrl+Maj+F / Ctrl+Maj+F3, Échap)",
        ["Help_Pick_File"] = "Sélectionner un fichier et insérer le chemin (Ctrl+Maj+O)",
        ["Help_Pick_Folder"] = "Sélectionner un dossier et insérer le chemin (Ctrl+Maj+E)",
        ["Help_Nav_F1"] = "Ouvrir cette boîte de dialogue d'aide (Ctrl+Maj+F1)",
        ["Help_Nav_Esc"] = "Fermer le dialogue actif et donner le focus au terminal",
        ["Help_Feature_1"] = "• Historique : Survoler le bord gauche ou Ctrl+Maj+H (Commandes) / Ctrl+Maj+L (Répertoires). Clic/Entrée pour insérer, clic droit pour exécuter.",
        ["Help_Feature_2"] = "• Glisser-déposer : Réorganiser les onglets en les faisant glisser avec le bouton gauche.",
        ["Help_Feature_3"] = "• Débordement : Boutons de défilement (‹ ›) et menu rapide (≡ ▾).",
        ["Help_Feature_4"] = "• Zoom : Ctrl++, Ctrl+-, Ctrl+0 ou Ctrl+Molette pour ajuster dynamiquement la taille.",
        ["Help_Feature_5"] = "• Persistance : Tous les onglets, répertoires et historiques sont enregistrés automatiquement.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "Espace de travail PowerShell haute performance",
        ["About_Version"] = "Version :",
        ["About_Framework"] = "Framework :",
        ["About_UI_Terminal"] = "UI & Terminal :",
        ["About_License"] = "Licence :",
        ["About_Font"] = "Police de terminal :",
        ["About_Font_Value"] = "FiraCode Nerd Font Mono (OFL-1.1)",
        ["About_Third_Party"] = "Licences tierces :",
        ["About_Third_Party_Value"] = "THIRD_PARTY_NOTICES.md (OFL, MIT)",
        ["About_GitHub"] = "Dépôt GitHub :",
        ["About_Built_With"] = "Développé avec :",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Conçu selon les principes de Clean Architecture & Clean Code.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Profils de terminal",
        ["Profiles_Modal_Subtitle"] = "Configurer les profils, modifier les chemins et ajouter de nouveaux shells",
        ["Profiles_Btn_Add"] = "+ Nouveau profil",
        ["Profiles_Btn_Edit"] = "Modifier",
        ["Profiles_Btn_Save"] = "Enregistrer",
        ["Profiles_Btn_Delete"] = "Supprimer",
        ["Profiles_Btn_Default"] = "Définir par défaut",
        ["Profiles_Btn_Cancel"] = "Annuler",
        ["Profiles_Btn_Browse"] = "Parcourir...",
        ["Profiles_Browse_Exe_Title"] = "Sélectionner le fichier exécutable",
        ["Profiles_Browse_Dir_Title"] = "Sélectionner le répertoire de travail",
        ["Dialog_PickFile_Title"] = "Sélectionner un fichier (insérer le chemin)",
        ["Dialog_PickFolder_Title"] = "Sélectionner un dossier (insérer le chemin)",
        ["Profiles_Field_Name"] = "Nom du profil",
        ["Profiles_Field_Path"] = "Chemin de l'exécutable",
        ["Profiles_Field_WorkingDir"] = "Répertoire de travail (par défaut : dossier utilisateur)",
        ["Profiles_Field_Args"] = "Arguments de démarrage (optionnel)",
        ["Profiles_Field_Icon"] = "Étiquette (ex. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Type d'émulation de shell",
        ["Profiles_Edit_Title"] = "Modifier le profil",
        ["Profiles_Create_Title"] = "Créer un nouveau profil",
        ["Profiles_Empty"] = "Aucun profil configuré.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "Aucun onglet de terminal actif",
        ["EmptyState_Description"] = "Sélectionnez un profil de terminal ci-dessous ou démarrez une nouvelle session avec les raccourcis.",
        ["EmptyState_QuickLaunch"] = "LANCEMENT RAPIDE",
        ["EmptyState_ShortcutsHint"] = "[ Ctrl+T Nouvel onglet  |  Ctrl+Maj+T Menu profils  |  Ctrl+Maj+F1 Aide ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Onglets récemment fermés",
        ["ClosedTabs_RestoreTooltip"] = "Restaurer l'onglet avec l'historique",
        ["ClosedTabs_RemoveTooltip"] = "Supprimer de l'historique",
        ["ClosedTabs_ClearAll"] = "Effacer l'historique",
        ["ClosedTabs_EmptyStateTitle"] = "Onglets récemment fermés",
        ["ClosedTabs_EmptyHint"] = "Aucun onglet fermé dans l'historique",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Rechercher dans le terminal...",
        ["Search_Terminal_Previous"] = "Occurrence précédente (Maj+Entrée)",
        ["Search_Terminal_Next"] = "Occurrence suivante (Entrée / Ctrl+Maj+F3)",
        ["Search_Terminal_Close"] = "Fermer la recherche (Échap)",
        ["Search_Terminal_NoResults"] = "Aucun résultat",
        ["Search_Terminal_Matches"] = "{0} sur {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Renommer l'onglet",
        ["Menu_Tab_ResetName"] = "Réinitialiser le nom de l'onglet",
        ["Menu_Tab_Color"] = "Couleur de l'onglet",
        ["Menu_Tab_Duplicate"] = "Dupliquer l'onglet",
        ["Menu_Tab_Close"] = "Fermer l'onglet",
        ["Menu_Tab_CloseOthers"] = "Fermer les autres onglets",
        ["Menu_Tab_CloseRight"] = "Fermer les onglets à droite",
        ["Color_Default"] = "Par défaut (aucune couleur)",
        ["Color_Red"] = "Rouge",
        ["Color_Orange"] = "Orange",
        ["Color_Yellow"] = "Jaune",
        ["Color_Green"] = "Vert",
        ["Color_Cyan"] = "Cyan",
        ["Color_Blue"] = "Bleu",
        ["Color_Purple"] = "Violet",
        ["Color_Pink"] = "Rose"
    };
}
