using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> PortugueseStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Definições & Sobre",
        ["Settings_App_Theme"] = "Tema da aplicação",
        ["Settings_Terminal_Theme"] = "Tema do terminal",
        ["Settings_Language"] = "Idioma",
        ["Settings_App_FontSize"] = "Tamanho da fonte da app",
        ["Settings_Terminal_FontSize"] = "Tamanho da fonte do terminal",
        ["Settings_Profiles_Title"] = "Perfis de terminal...",
        ["Settings_Help_Title"] = "Ajuda & Atalhos",
        ["Settings_About_Title"] = "Sobre o MultiShell",
        ["Theme_Dark"] = "Escuro",
        ["Theme_Light"] = "Claro",
        ["FontSize_Level_1"] = "Muito pequeno (1)",
        ["FontSize_Level_2"] = "Pequeno (2)",
        ["FontSize_Level_3"] = "Padrão (3)",
        ["FontSize_Level_4"] = "Grande (4)",
        ["FontSize_Level_5"] = "Muito grande (5)",
        ["FontSize_Default_Badge"] = "Padrão",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "Novo separador (Ctrl+Shift+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "Novo separador {0} (Ctrl+Shift+T)",
        ["Btn_Select_Shell_Tooltip"] = "Selecionar tipo de terminal",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Linha de comandos (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Histórico do separador (Ctrl+Shift+H / Ctrl+Shift+L)",
        ["Btn_Tab_History_Text"] = "Histórico",
        ["Btn_Tab_Menu_Tooltip"] = "Visão geral dos separadores (Ctrl+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Deslocar separadores para a esquerda",
        ["Btn_Tab_Scroll_Right"] = "Deslocar separadores para a direita",
        ["Btn_Tab_Close_Tooltip"] = "Fechar separador (Ctrl+Shift+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "SEPARADORES ABERTOS",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Shift+Tab ▴  |  Solte Ctrl para abrir  |  Esc Cancelar ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Navegar  |  Clique/Enter Abrir  |  Esc Fechar ]",
        ["Tab_Switcher_Count"] = "{0} de {1} separadores",

        // Drawer
        ["Drawer_Title"] = "HISTÓRICO",
        ["Drawer_Tab_Commands"] = "Comandos",
        ["Drawer_Tab_Directories"] = "Diretórios",
        ["Drawer_Tab_Global"] = "Global",
        ["Drawer_Search_Commands_Placeholder"] = "Filtrar comandos...",
        ["Drawer_Search_Directories_Placeholder"] = "Filtrar diretórios...",
        ["Drawer_Search_Global_Placeholder"] = "Filtrar todos os comandos e caminhos...",
        ["Drawer_Empty_Commands"] = "Nenhum comando executado neste separador.",
        ["Drawer_Empty_Directories"] = "Nenhum diretório registado neste separador.",
        ["Drawer_Empty_Global"] = "Nenhum comando ou caminho registado.",
        ["Drawer_Hint"] = "[ ▲/▼ Navegar  |  Clique/Enter Inserir  |  Clique direito Executar  |  Esc Fechar ]",

        // Help Modal
        ["Help_Modal_Title"] = "Atalhos de teclado & Utilização",
        ["Help_Section_Navigation"] = "ATALHOS",
        ["Help_Section_Tabs"] = "GESTÃO DE SEPARADORES",
        ["Help_Section_History"] = "PAINEL DE HISTÓRICO",
        ["Help_Section_Features"] = "FUNCIONALIDADES",
        ["Help_Close_Button"] = "Fechar",
        ["Help_Tab_New"] = "Abrir novo separador PowerShell",
        ["Help_Tab_Dup"] = "Duplicar separador ativo no diretório atual",
        ["Help_Tab_Next_Prev"] = "Selecionar separador seguinte / anterior",
        ["Help_Tab_Jump"] = "Saltar diretamente para o separador 1..8 ou último (9)",
        ["Help_Tab_Close"] = "Fechar separador ativo",
        ["Help_Tab_Move"] = "Mover separador ativo para a esquerda / direita",
        ["Help_Term_Newline"] = "Inserir nova linha no terminal sem executar comando",
        ["Help_Zoom_Shortcuts"] = "Aumentar / diminuir / repor tamanho da fonte do terminal (também Ctrl+Roda do rato)",
        ["Help_Scroll_Shortcuts"] = "Deslocar para cima / para baixo no buffer do terminal",
        ["Help_Buffer_Clear"] = "Limpar ecrã e buffer de deslocamento do terminal",
        ["Help_Copy_Paste"] = "Copiar / colar texto sem interrupção de sinal",
        ["Help_Hist_Toggle"] = "Alternar painel de histórico (Navegar com ▲/▼, Enter)",
        ["Help_Hist_Commands"] = "Alternar histórico de comandos (▲/▼, Enter)",
        ["Help_Hist_Directories"] = "Alternar histórico de diretórios (▲/▼, Enter)",
        ["Help_Hist_Global"] = "Alternar histórico global (▲/▼, Enter)",
        ["Help_Search_Terminal"] = "Abrir/fechar pesquisa no terminal (Ctrl+Shift+F / Ctrl+Shift+F3, Esc)",
        ["Help_Pick_File"] = "Selecionar ficheiro e inserir caminho (Ctrl+Shift+O)",
        ["Help_Pick_Folder"] = "Selecionar pasta e inserir caminho (Ctrl+Shift+B)",
        ["Help_Open_Explorer"] = "Abrir explorador de ficheiros na pasta atual (Ctrl+Shift+E)",
        ["Help_Nav_F1"] = "Abrir este diálogo de ajuda (Ctrl+Shift+F1)",
        ["Help_Nav_Esc"] = "Fechar sobreposição / diálogo ativo e focar no terminal",
        ["Help_Feature_1"] = "• Histórico do separador: Passe o rato na margem esquerda ou prima Ctrl+Shift+H (Comandos) / Ctrl+Shift+L (Diretórios). Clique esquerdo/Enter para inserir, clique direito para executar.",
        ["Help_Feature_2"] = "• Arrastar & Largar: Reordene os separadores arrastando com o botão esquerdo do rato.",
        ["Help_Feature_3"] = "• Transbordo de separadores: Botões de deslocamento (‹ ›) e menu rápido (≡ ▾) surgem quando os separadores excedem a janela.",
        ["Help_Feature_4"] = "• Zoom: Ctrl++, Ctrl+-, Ctrl+0 ou Ctrl+Roda do rato para dimensionar dinamicamente a fonte.",
        ["Help_Feature_5"] = "• Persistência: Todos os separadores, diretórios de trabalho e históricos persistem automaticamente entre reinícios.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "Espaço de trabalho PowerShell de alto desempenho",
        ["About_Version"] = "Versão:",
        ["About_Framework"] = "Framework:",
        ["About_UI_Terminal"] = "UI & Terminal:",
        ["About_License"] = "Licença:",
        ["About_GitHub"] = "Repositório GitHub:",
        ["About_Built_With"] = "Criado com:",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Criado com os princípios de Clean Architecture & Clean Code.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Perfis de terminal",
        ["Profiles_Modal_Subtitle"] = "Configurar perfis de terminal, caminhos, argumentos e adicionar shells personalizadas",
        ["Profiles_Btn_Add"] = "+ Novo perfil",
        ["Profiles_Btn_Edit"] = "Editar",
        ["Profiles_Btn_Delete"] = "Eliminar",
        ["Profiles_Btn_Save"] = "Guardar",
        ["Profiles_Btn_Cancel"] = "Cancelar",
        ["Profiles_Btn_Reset"] = "Repor predefinições",
        ["Profiles_Btn_Browse"] = "Procurar...",
        ["Profiles_Browse_Exe_Title"] = "Selecionar ficheiro executável",
        ["Profiles_Browse_Dir_Title"] = "Selecionar diretório de trabalho",
        ["Dialog_PickFile_Title"] = "Selecionar ficheiro (inserir caminho)",
        ["Dialog_PickFolder_Title"] = "Selecionar pasta (inserir caminho)",
        ["Profiles_Field_Name"] = "Nome do perfil",
        ["Profiles_Field_Path"] = "Caminho do executável",
        ["Profiles_Field_WorkingDir"] = "Diretório de trabalho (predefinição: pasta do utilizador)",
        ["Profiles_Field_Args"] = "Argumentos (opcional)",
        ["Profiles_Field_Icon"] = "Etiqueta (ex. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Tipo de emulação de shell",
        ["Profiles_Edit_Title"] = "Editar perfil",
        ["Profiles_Create_Title"] = "Criar novo perfil",
        ["Profiles_Empty"] = "Nenhum perfil configurado.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "Sem separadores de terminal ativos",
        ["EmptyState_Description"] = "Selecione um perfil de terminal abaixo ou inicie uma nova sessão através de atalhos.",
        ["EmptyState_QuickLaunch"] = "INÍCIO RÁPIDO",
        ["EmptyState_ShortcutsHint"] = "[ Ctrl+T Novo separador  |  Ctrl+Shift+T Menu de perfis  |  Ctrl+Shift+F1 Ajuda ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Separadores fechados recentemente",
        ["ClosedTabs_RestoreTooltip"] = "Restaurar separador com histórico",
        ["ClosedTabs_RemoveTooltip"] = "Remover do histórico",
        ["ClosedTabs_ClearAll"] = "Limpar histórico",
        ["ClosedTabs_EmptyStateTitle"] = "Separadores fechados recentemente",
        ["ClosedTabs_EmptyHint"] = "Nenhum separador fechado no histórico",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Localizar no terminal...",
        ["Search_Terminal_Previous"] = "Correspondência anterior (Shift+Enter)",
        ["Search_Terminal_Next"] = "Próxima correspondência (Enter / Ctrl+Shift+F3)",
        ["Search_Terminal_Close"] = "Fechar pesquisa (Esc)",
        ["Search_Terminal_NoResults"] = "Nenhum resultado",
        ["Search_Terminal_Matches"] = "{0} de {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Mudar o nome do separador",
        ["Menu_Tab_ResetName"] = "Repor nome do separador",
        ["Menu_Tab_Color"] = "Cor do separador",
        ["Menu_Tab_Duplicate"] = "Duplicar separador",
        ["Menu_Tab_OpenInExplorer"] = "Abrir no explorador de ficheiros",
        ["Menu_Tab_Close"] = "Fechar separador",
        ["Menu_Tab_CloseOthers"] = "Fechar outros separadores",
        ["Menu_Tab_CloseRight"] = "Fechar separadores à direita",
        ["Color_Default"] = "Padrão (sem cor)",
        ["Color_Red"] = "Vermelho",
        ["Color_Orange"] = "Laranja",
        ["Color_Yellow"] = "Amarelo",
        ["Color_Green"] = "Verde",
        ["Color_Cyan"] = "Ciano",
        ["Color_Blue"] = "Azul",
        ["Color_Purple"] = "Roxo",
        ["Color_Pink"] = "Rosa"
    };
}
