using System;
using System.Collections.Generic;

namespace MultiShell.Services;

public partial class LocalizationService
{
    private static readonly Dictionary<string, string> SpanishStrings = new(StringComparer.OrdinalIgnoreCase)
    {
        // Settings Menu
        ["Settings_Menu_Title"] = "Configuración & Acerca de",
        ["Settings_App_Theme"] = "Tema de la aplicación",
        ["Settings_Terminal_Theme"] = "Tema del terminal",
        ["Settings_Language"] = "Idioma",
        ["Settings_App_FontSize"] = "Tamaño de fuente de la app",
        ["Settings_Terminal_FontSize"] = "Tamaño de fuente del terminal",
        ["Settings_Profiles_Title"] = "Perfiles de terminal...",
        ["Settings_Help_Title"] = "Ayuda & Atajos",
        ["Settings_About_Title"] = "Acerca de MultiShell",
        ["Theme_Dark"] = "Oscuro",
        ["Theme_Light"] = "Claro",
        ["FontSize_Level_1"] = "Muy pequeño (1)",
        ["FontSize_Level_2"] = "Pequeño (2)",
        ["FontSize_Level_3"] = "Estándar (3)",
        ["FontSize_Level_4"] = "Grande (4)",
        ["FontSize_Level_5"] = "Muy grande (5)",
        ["FontSize_Default_Badge"] = "Estándar",
        ["Lang_German"] = "Deutsch",
        ["Lang_English"] = "English",
        ["Lang_French"] = "Français",
        ["Lang_Spanish"] = "Español",
        ["Lang_Italian"] = "Italiano",
        ["Lang_Portuguese"] = "Português",

        // Toolbar & Tabs
        ["Btn_New_Tab_Tooltip"] = "Nueva pestaña (Ctrl+Mayús+T)",
        ["Btn_New_Tab_With_Shell_Tooltip"] = "Nueva pestaña {0} (Ctrl+Mayús+T)",
        ["Btn_Select_Shell_Tooltip"] = "Seleccionar tipo de terminal",
        ["Shell_PowerShell"] = "PowerShell",
        ["Shell_NuShell"] = "NuShell",
        ["Shell_WSL"] = "WSL (Linux)",
        ["Shell_CMD"] = "Símbolo del sistema (CMD)",
        ["Btn_Tab_History_Tooltip"] = "Historial de pestañas (Ctrl+Mayús+H / Ctrl+Mayús+L)",
        ["Btn_Tab_History_Text"] = "Historial",
        ["Btn_Tab_Menu_Tooltip"] = "Vista general de pestañas (Ctrl+Tab)",
        ["Btn_Tab_Scroll_Left"] = "Desplazar pestañas a la izquierda",
        ["Btn_Tab_Scroll_Right"] = "Desplazar pestañas a la derecha",
        ["Btn_Tab_Close_Tooltip"] = "Cerrar pestaña (Ctrl+Mayús+W)",

        // Tab Switcher Overlay
        ["Tab_Switcher_Title"] = "VISTA GENERAL DE PESTAÑAS",
        ["Tab_Switcher_Hint_Keyboard"] = "[ Tab ▾  |  Mayús+Tab ▴  |  Soltar Ctrl para abrir  |  Esc Cancelar ]",
        ["Tab_Switcher_Hint_Click"] = "[ ▲/▼ Navegar  |  Clic/Enter Abrir  |  Esc Cerrar ]",
        ["Tab_Switcher_Count"] = "{0} de {1} pestañas",

        // Drawer
        ["Drawer_Title"] = "HISTORIAL",
        ["Drawer_Tab_Commands"] = "Comandos",
        ["Drawer_Tab_Directories"] = "Directorios",
        ["Drawer_Tab_Global"] = "Global",
        ["Drawer_Search_Commands_Placeholder"] = "Filtrar comandos...",
        ["Drawer_Search_Directories_Placeholder"] = "Filtrar directorios...",
        ["Drawer_Search_Global_Placeholder"] = "Filtrar todos los comandos y rutas...",
        ["Drawer_Empty_Commands"] = "Aún no se han ejecutado comandos en esta pestaña.",
        ["Drawer_Empty_Directories"] = "Aún no se han registrado directorios en esta pestaña.",
        ["Drawer_Empty_Global"] = "Aún no se han registrado comandos o rutas.",
        ["Drawer_Hint"] = "[ ▲/▼ Navegar  |  Clic/Enter Insertar  |  Clic derecho Ejecutar  |  Esc Cerrar ]",

        // Help Modal
        ["Help_Modal_Title"] = "Atajos de teclado & Uso",
        ["Help_Section_Navigation"] = "ATAJOS",
        ["Help_Section_Tabs"] = "GESTIÓN DE PESTAÑAS",
        ["Help_Section_History"] = "PANEL DE HISTORIAL",
        ["Help_Section_Features"] = "CARACTERÍSTICAS",
        ["Help_Close_Button"] = "Cerrar",
        ["Help_Tab_New"] = "Abrir una nueva pestaña PowerShell",
        ["Help_Tab_Dup"] = "Duplicar la pestaña activa en el directorio actual",
        ["Help_Tab_Next_Prev"] = "Seleccionar siguiente / anterior pestaña (cíclico)",
        ["Help_Tab_Jump"] = "Ir directamente a la pestaña 1..8 o a la última (9)",
        ["Help_Tab_Close"] = "Cerrar pestaña activa",
        ["Help_Tab_Move"] = "Mover pestaña activa a la izquierda / derecha",
        ["Help_Term_Newline"] = "Insertar salto de línea en el terminal sin ejecutar",
        ["Help_Zoom_Shortcuts"] = "Aumentar / disminuir / restablecer fuente del terminal (o Ctrl+Rueda)",
        ["Help_Scroll_Shortcuts"] = "Desplazarse arriba / abajo en el búfer del terminal",
        ["Help_Buffer_Clear"] = "Limpiar pantalla y búfer de desplazamiento del terminal",
        ["Help_Copy_Paste"] = "Copiar / pegar texto sin interrumpir señales",
        ["Help_Hist_Toggle"] = "Alternar panel de historial (Navegar con ▲/▼, Enter)",
        ["Help_Hist_Commands"] = "Alternar historial de comandos (▲/▼, Enter)",
        ["Help_Hist_Directories"] = "Alternar historial de directorios (▲/▼, Enter)",
        ["Help_Hist_Global"] = "Alternar historial global (▲/▼, Enter)",
        ["Help_Search_Terminal"] = "Abrir/cerrar búsqueda en la terminal (Ctrl+Mayús+F / Ctrl+Mayús+F3, Esc)",
        ["Help_Pick_File"] = "Seleccionar archivo e insertar ruta (Ctrl+Mayús+O)",
        ["Help_Pick_Folder"] = "Seleccionar carpeta e insertar ruta (Ctrl+Mayús+E)",
        ["Help_Nav_F1"] = "Abrir este diálogo de ayuda (Ctrl+Mayús+F1)",
        ["Help_Nav_Esc"] = "Cerrar el diálogo activo y enfocar el terminal",
        ["Help_Feature_1"] = "• Historial: Pase el ratón por el borde izquierdo o Ctrl+Mayús+H (Comandos) / Ctrl+Mayús+L (Directorios). Clic/Enter para insertar, clic derecho para ejecutar.",
        ["Help_Feature_2"] = "• Arrastrar y soltar: Reordene las pestañas arrastrándolas con el ratón.",
        ["Help_Feature_3"] = "• Desbordamiento: Botones de desplazamiento (‹ ›) y menú rápido (≡ ▾).",
        ["Help_Feature_4"] = "• Zoom: Ctrl++, Ctrl+-, Ctrl+0 o Ctrl+Rueda para escalar la fuente.",
        ["Help_Feature_5"] = "• Persistencia: Todas las pestañas, directorios e historiales se guardan.",

        // About Modal
        ["About_Modal_Title"] = "MultiShell",
        ["About_Modal_Subtitle"] = "Espacio de trabajo PowerShell de alto rendimiento",
        ["About_Version"] = "Versión:",
        ["About_Framework"] = "Framework:",
        ["About_UI_Terminal"] = "UI & Terminal:",
        ["About_License"] = "Licencia:",
        ["About_GitHub"] = "Repositorio GitHub:",
        ["About_Built_With"] = "Creado con:",
        ["About_Built_With_Value"] = "Google Gemini & Antigravity",
        ["About_Footer"] = "Diseñado con los principios de Clean Architecture & Clean Code.",
        ["About_OK_Button"] = "OK",

        // Profiles Modal
        ["Profiles_Modal_Title"] = "Perfiles de terminal",
        ["Profiles_Modal_Subtitle"] = "Configurar perfiles, modificar rutas y agregar terminales personalizados",
        ["Profiles_Btn_Add"] = "+ Nuevo perfil",
        ["Profiles_Btn_Edit"] = "Editar",
        ["Profiles_Btn_Delete"] = "Eliminar",
        ["Profiles_Btn_Save"] = "Guardar",
        ["Profiles_Btn_Cancel"] = "Cancelar",
        ["Profiles_Btn_Reset"] = "Restablecer valores predeterminados",
        ["Profiles_Btn_Browse"] = "Examinar...",
        ["Profiles_Browse_Exe_Title"] = "Seleccionar archivo ejecutable",
        ["Profiles_Browse_Dir_Title"] = "Seleccionar directorio de trabajo",
        ["Dialog_PickFile_Title"] = "Seleccionar archivo (insertar ruta)",
        ["Dialog_PickFolder_Title"] = "Seleccionar carpeta (insertar ruta)",
        ["Profiles_Field_Name"] = "Nombre del perfil",
        ["Profiles_Field_Path"] = "Ruta del archivo ejecutable",
        ["Profiles_Field_WorkingDir"] = "Directorio de trabajo (predeterminado: carpeta de usuario)",
        ["Profiles_Field_Args"] = "Argumentos de inicio (opcional)",
        ["Profiles_Field_Icon"] = "Etiqueta (ej. PS, CMD, GIT)",
        ["Profiles_Field_ShellType"] = "Tipo de emulación de shell",
        ["Profiles_Edit_Title"] = "Editar perfil",
        ["Profiles_Create_Title"] = "Crear nuevo perfil",
        ["Profiles_Empty"] = "No hay perfiles configurados.",

        // Empty State Welcome Dashboard (REQ-UI-008)
        ["EmptyState_Title"] = "No hay pestañas de terminal activas",
        ["EmptyState_Description"] = "Seleccione un perfil de terminal a continuación o inicie una nueva sesión mediante atajos.",
        ["EmptyState_QuickLaunch"] = "INICIO RÁPIDO",
        ["EmptyState_ShortcutsHint"] = "[ Ctrl+T Nueva pestaña  |  Ctrl+Mayús+T Menú de perfiles  |  Ctrl+Mayús+F1 Ayuda ]",

        // Recently Closed Tabs History (REQ-TAB-021)
        ["ClosedTabs_Title"] = "Pestañas cerradas recientemente",
        ["ClosedTabs_RestoreTooltip"] = "Restaurar pestaña con historial",
        ["ClosedTabs_RemoveTooltip"] = "Eliminar del historial",
        ["ClosedTabs_ClearAll"] = "Borrar historial",
        ["ClosedTabs_EmptyStateTitle"] = "Pestañas cerradas recientemente",
        ["ClosedTabs_EmptyHint"] = "No hay pestañas cerradas en el historial",

        // In-Terminal Search (REQ-TERM-006)
        ["Search_Terminal_Watermark"] = "Buscar en la terminal...",
        ["Search_Terminal_Previous"] = "Coincidencia anterior (Mayús+Intro)",
        ["Search_Terminal_Next"] = "Siguiente coincidencia (Intro / Ctrl+Mayús+F3)",
        ["Search_Terminal_Close"] = "Cerrar búsqueda (Esc)",
        ["Search_Terminal_NoResults"] = "Sin resultados",
        ["Search_Terminal_Matches"] = "{0} de {1}",

        // Tab Context Menu & Renaming (REQ-TAB-020)
        ["Menu_Tab_Rename"] = "Cambiar nombre de pestaña",
        ["Menu_Tab_ResetName"] = "Restablecer nombre de pestaña",
        ["Menu_Tab_Color"] = "Color de pestaña",
        ["Menu_Tab_Duplicate"] = "Duplicar pestaña",
        ["Menu_Tab_Close"] = "Cerrar pestaña",
        ["Menu_Tab_CloseOthers"] = "Cerrar las demás pestañas",
        ["Menu_Tab_CloseRight"] = "Cerrar pestañas a la derecha",
        ["Color_Default"] = "Predeterminado (sin color)",
        ["Color_Red"] = "Rojo",
        ["Color_Orange"] = "Naranja",
        ["Color_Yellow"] = "Amarillo",
        ["Color_Green"] = "Verde",
        ["Color_Cyan"] = "Cian",
        ["Color_Blue"] = "Azul",
        ["Color_Purple"] = "Morado",
        ["Color_Pink"] = "Rosa"
    };
}
